# Generated by Django 3.1.7 on 2021-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nonse',
            field=models.TextField(default='1000000'),
        ),
    ]
