# Generated by Django 3.1.7 on 2021-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210405_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nonse',
            field=models.TextField(default='7251685223'),
        ),
    ]
