# Generated by Django 3.1.7 on 2021-04-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210405_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nonse',
            field=models.TextField(default='9302782116.595612'),
        ),
    ]
